/*
 * PN registry API
 *
 * Evidence and tracking system of sick-leave (PN) records for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbojko@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pn_registry

import (
	"github.com/bmathus/pnregistry-webapi/internal/pn_registry/handlers"
	"github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
	group := engine.Group("/api")

	// Register each route directly in the /api group
	group.POST("/records/", handlers.CreateRecord)
	group.DELETE("/records/:recordId/", handlers.DeleteRecord)
	group.GET("/records/:recordId/", handlers.GetRecord)
	group.GET("/records/", handlers.GetRecordAll)
	group.PUT("/records/:recordId/", handlers.UpdateRecord)
}
