/*
 * PN registry API
 *
 * Evidence and tracking system of sick-leave (PN) records for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbojko@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package pn_registry

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type PnRegistryRecordsAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateRecord - Saves new PN record into list of all PN records
   CreateRecord(ctx *gin.Context)

    // DeleteRecord - Deletes specific PN record
   DeleteRecord(ctx *gin.Context)

    // GetRecord - Provides details about specific PN record
   GetRecord(ctx *gin.Context)

    // GetRecordAll - Provides list of all PN records
   GetRecordAll(ctx *gin.Context)

    // UpdateRecord - Updates specific PN record
   UpdateRecord(ctx *gin.Context)

 }

// partial implementation of PnRegistryRecordsAPI - all functions must be implemented in add on files
type implPnRegistryRecordsAPI struct {

}

func newPnRegistryRecordsAPI() PnRegistryRecordsAPI {
  return &implPnRegistryRecordsAPI{}
}

func (this *implPnRegistryRecordsAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/records/", this.CreateRecord)
  routerGroup.Handle( http.MethodDelete, "/records/:recordId/", this.DeleteRecord)
  routerGroup.Handle( http.MethodGet, "/records/:recordId/", this.GetRecord)
  routerGroup.Handle( http.MethodGet, "/records/", this.GetRecordAll)
  routerGroup.Handle( http.MethodPut, "/records/:recordId/", this.UpdateRecord)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateRecord - Saves new PN record into list of all PN records
// func (this *implPnRegistryRecordsAPI) CreateRecord(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteRecord - Deletes specific PN record
// func (this *implPnRegistryRecordsAPI) DeleteRecord(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetRecord - Provides details about specific PN record
// func (this *implPnRegistryRecordsAPI) GetRecord(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetRecordAll - Provides list of all PN records
// func (this *implPnRegistryRecordsAPI) GetRecordAll(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateRecord - Updates specific PN record
// func (this *implPnRegistryRecordsAPI) UpdateRecord(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

