/*
 * PN registry API
 *
 * Evidence and tracking system of sick-leave (PN) records for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbojko@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pn_registry

type Record struct {

	// Unique identifier of PN record
	Id string `json:"id,omitempty"`

	// Full name of pacient whom the PN record was issued
	FullName string `json:"full_name,omitempty"`
}
