/*
 * PN registry API
 *
 * Evidence and tracking system of sick-leave (PN) records for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbojko@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pn_registry

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newPnRegistryRecordsAPI()
    api.addRoutes(group)
  }
  
}