apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb-pnregistry-webapi
spec:
  replicas: 1
  selector:
      matchLabels:
        pod: mb-pnregistry-webapi-label
  template:
      metadata:
        labels:
          pod: mb-pnregistry-webapi-label
      spec:
        volumes:
        - name: init-scripts
          configMap:
            name: mb-pnregistry-webapi-mongodb-init
        initContainers:
        - name: init-mongodb
          image: mongo:latest
          imagePullPolicy: Always
          command: ['mongosh', "--nodb", '-f', '/scripts/init-db.js']
          volumeMounts:
          - name: init-scripts
            mountPath: /scripts
          env:
             - name: PN_REGISTRY_API_PORT
               value: "8080"
             - name: PN_REGISTRY_API_MONGODB_HOST
               value: mongodb
             - name: PN_REGISTRY_API_MONGODB_PORT
               value: "27017"
             - name: PN_REGISTRY_API_MONGODB_USERNAME
               value: ""
             - name: PN_REGISTRY_API_MONGODB_PASSWORD
               value: ""
             - name: PN_REGISTRY_API_MONGODB_DATABASE
               valueFrom:
                 configMapKeyRef:
                   name: mb-pnregistry-webapi-config
                   key: database
             - name: PN_REGISTRY_API_MONGODB_COLLECTION
               valueFrom:
                 configMapKeyRef:
                   name: mb-pnregistry-webapi-config
                   key: collection
             - name: RETRY_CONNECTION_SECONDS
               value: "5"
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.01"
            limits:
              memory: "256Mi"
              cpu: "0.1"

        containers:
        - name: mb-pnregistry-webapi-container
          image: thamako3/pnregistry-webapi:latest
          imagePullPolicy: Always
          ports:
          - name: webapi-port
            containerPort: 8080
          env:
            - name: PN_REGISTRY_API_ENVIRONMENT
              value: production
            - name: PN_REGISTRY_API_PORT
              value: "8080"
            - name: PN_REGISTRY_API_MONGODB_HOST
              value: mongodb
            - name: PN_REGISTRY_API_MONGODB_PORT
              value: "27017"
              # change to actual value
            - name: PN_REGISTRY_API_MONGODB_USERNAME
              value: ""
              #change to actual value
            - name: PN_REGISTRY_API_MONGODB_PASSWORD
              value: ""
            - name: PN_REGISTRY_API_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mb-pnregistry-webapi-config
                  key: database
            - name: PN_REGISTRY_API_MONGODB_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: mb-pnregistry-webapi-config
                  key: collection
            - name: PN_REGISTRY_API_MONGODB_TIMEOUT_SECONDS
              value: "5"
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.01"
            limits:
              memory: "512Mi"
              cpu: "0.3"
            
        - name: openapi-ui
          image: swaggerapi/swagger-ui
          imagePullPolicy: Always
          ports:
          - name: api-ui
            containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name:   URL
              value: /openapi
            - name: BASE_URL
              value: /openapi-ui
            - name: FILTER
              value: 'true'
            - name: DISPLAY_OPERATION_ID
              value: 'true'
          resources:
              requests:
                  memory: "16M"
                  cpu: "0.01"
              limits:
                  memory: "64M"
                  cpu: "0.1"