apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: mb-pnregistry-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: mb-pnregistry-webapi-config
    literals:
      - database=pn-registry
      - collection=record
patches:
 - path: patches/webapi.deployment.yaml
   target:
     group: apps
     version: v1
     kind: Deployment
     name: mb-pnregistry-webapi