kind: Service
apiVersion: v1
metadata:
  name: mb-pnregistry-webapi
spec:
  selector:
    pod: mb-pnregistry-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port